New Changes

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -1,13 +1,14 @@
-name: SFDX Code Scan Delta
-
 on:
-  push:
+  pull_request:
     branches:
       - "**"
 
 jobs:
-  installcli:
+  quality-gate-code-check:
     runs-on: ubuntu-latest
+    outputs:
+      scanner-report-path: ${{ steps.upload-report.outputs.artifact-path }}
+      block-pr: ${{ steps.block-check.outputs.block-status }}
     steps:
       - uses: actions/checkout@v3
         with:
@@ -18,29 +19,22 @@ jobs:
         with:
           node-version: 20.x
 
-      - name: Install CLI
+      - name: Install Salesforce CLI
         run: npm install @salesforce/cli --global
 
       - name: Install Scanner Plugin
         run: sf plugins install @salesforce/sfdx-scanner
 
-      - name: Verify SFDX CLI Installation
+      - name: Verify Salesforce CLI Installation
         run: sf --version
 
-      - name: Verify SFDX Scanner Plugin Installation
+      - name: Verify Scanner Plugin Installation
         run: sf plugins --core
 
       - name: Get changed files and lines (for .cls and .lwc files)
         id: get-changes
         run: |
-          # Check if the repository is shallow and unshallow if necessary
-          if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
-            echo "Repository is shallow, unshallowing..."
-            git fetch --unshallow || { echo "Failed to unshallow the repository"; exit 1; }
-          else
-            echo "Repository is not shallow, skipping unshallow."
-          fi
-
+          git fetch --unshallow || true
           if [ "$(git rev-list --count HEAD)" -gt "1" ]; then
             echo "Fetching changed files and lines between HEAD~1 and HEAD"
             git diff --unified=0 HEAD~1 HEAD > changes.diff || { echo "Failed to get git diff"; exit 1; }
@@ -48,13 +42,11 @@ jobs:
             echo "No previous commit to compare to." > changes.diff
           fi
 
-          # Check if diff has any content
           if [ ! -s changes.diff ]; then
             echo "No changes detected between HEAD~1 and HEAD."
             exit 0
           fi
 
-          # Extract and print only the changed lines and line numbers from .cls and .lwc files
           echo "Processing changes for .cls and .lwc files only..."
           awk '
             BEGIN {valid_file=0} 
@@ -64,7 +56,6 @@ jobs:
             /^[+][^+]/ && valid_file {print "Line", start + line_offset++, ":", substr($0, 2)}  
           ' changes.diff | grep -v '^+++' > changed_cls_lwc_lines.txt
 
-          # Check if any relevant changes were found in .cls or .lwc files
           if [ ! -s changed_cls_lwc_lines.txt ]; then
             echo "No changes detected in .cls or .lwc files."
             exit 0
@@ -74,140 +65,138 @@ jobs:
 
       - name: Run SFDX Scanner on Changed Files and Lines
         run: |
-          # Get the changed .cls and .lwc files from the diff
           files=$(grep -E '^\+\+\+ b/.*(\.cls|\.lwc)$' changes.diff | sed 's/+++ b\///')
-
-          # Check if files were found
           if [ -z "$files" ]; then
             echo "No changed .cls or .lwc files detected."
             exit 0
           fi
 
-          # Declare an array to store the line numbers
           declare -a line_numbers_array=()
 
-          # Loop through each changed file
           while IFS= read -r file; do
             echo "Processing file: $file"
-            
-            file=$(echo "$file" | tr -d '"') # Clean up the file path
-
-            # Extract the actual changed lines and line numbers for the specific file
+            file=$(echo "$file" | tr -d '"')
             changed_lines=$(grep -A 1000 "$file" changes.diff | grep '^\+' | sed 's/^+//')
             line_numbers=$(grep -A 1000 "$file" changes.diff | grep '^@@' | awk '{print $2}' | cut -d',' -f1 | sed 's/-//')
 
-            echo "Changed lines in $file:"
-            echo "$changed_lines"
-            echo "Line numbers corresponding to the changed lines in $file:"
-            echo "$line_numbers"
-
-            # Reset the index for each file
             current_line_number=$(echo "$line_numbers" | head -1)
             echo "Starting line number: $current_line_number"
 
-            # Iterate through changed lines
             while IFS= read -r line; do
-              echo "Mapping changed line: '$line' to original line number: $current_line_number"
               echo "Running SFDX Scanner on file: $file at line number: $current_line_number..."
-
-              # Run the SFDX scanner on each file and line
-              sf scanner:run --target "$file" --format "csv" --outfile "scanner-report.csv" || {
-                echo "Scanner run failed or no issues found for $file, continuing with other files."
-              }
-
-              # Store the current line number in the array
+              sf scanner:run --target "$file" --format "csv" --outfile "scanner-report.csv" || { echo "Scanner run failed or no issues found for $file, continuing with other files."; }
               line_numbers_array+=("$current_line_number")
               current_line_number=$((current_line_number + 1))
             done <<< "$changed_lines"
-
           done <<< "$files"
 
-          # Store the line numbers array in a file for later use
           echo "${line_numbers_array[*]}" > line_numbers.txt
           cat line_numbers.txt
 
       - name: Filter Scanner Report by Line Numbers
         run: |
-          # Read the line numbers from the file
           current_line_number_list=$(cat line_numbers.txt)
-          echo "Current_Line_Number_List: $current_line_number_list"
-
-          # Ensure there are no leading/trailing spaces in the line number list
           current_line_number_list=$(echo $current_line_number_list | xargs)
-
           echo "Filtering scanner report for the following line numbers: $current_line_number_list"
-
-          # Use FPAT to correctly parse the CSV columns, treating each quoted field as a separate field
           awk -v lines="$current_line_number_list" '
           BEGIN {
-            FPAT = "([^,]+)|(\"[^\"]+\")";  # Define how to match CSV fields
+            FPAT = "([^,]+)|(\"[^\"]+\")";
             split(lines, arr, " ");
             for (i in arr) {
-              valid[arr[i]] = 1;  # Treat line numbers as strings
+              valid[arr[i]] = 1;
             }
           }
-          NR == 1 || (substr($4, 2, length($4)-2) in valid) {  # Check if Line (stripped of quotes) is in valid lines
-            print $0;  # Only print matching rows, no debug output
+          NR == 1 || (substr($4, 2, length($4)-2) in valid) {
+            print $0;
           }
           ' scanner-report.csv > filtered-scanner-report.csv
-
-          echo "Filtered scanner report:"
           cat filtered-scanner-report.csv
 
-      - name: Install mailx
-        run: sudo apt-get install -y mailutils
-
-      - name: Get Repository and Branch Info
-        id: get-info
+      - name: Block PR merge if severity violations are found
+        id: block-check
         run: |
-          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
-          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
-          COMMIT_LABEL=$(git log -1 --pretty=format:'%s')
-          FILE_TITLE="Code Scanner Delta Report_${REPO_NAME}_${BRANCH_NAME}_${COMMIT_LABEL}"
-          echo "FILE_TITLE=${FILE_TITLE}" >> $GITHUB_ENV
+          if [ -f filtered-scanner-report.csv ]; then
+            severity_fail_count=$(awk -F',' '{gsub(/^ *| *$/, "", $2); if($2 == "\"3\"") count++} END {print count}' filtered-scanner-report.csv)
+            echo "Severity 3 issues count: $severity_fail_count"
+            if [ "$severity_fail_count" -gt 0 ]; then
+              echo "Blocking your pull request due to severity 3 vulnerabilities found."
+              echo "::set-output name=block-status::true"
+              exit 1
+            else
+              echo "No severity 3 vulnerabilities found. Proceeding with Approval."
+              echo "::set-output name=block-status::false"
+            fi
+          else
+            echo "No filtered scanner report found."
+            exit 1
+          fi
 
-      - name: Upload Filtered Scanner Report as Artifact
+      - name: Upload Filtered Scanner Report
+        id: upload-report
         uses: actions/upload-artifact@v3
         with:
-          name: ${{ env.FILE_TITLE }}
+          name: SFDX_Code_Scan_Report
           path: filtered-scanner-report.csv
 
-      - name: Get Pusher's Email
-        id: get-pusher-email
-        run: |
-          COMMIT_SHA=${{ github.sha }}
-          REPO=${{ github.repository }}
-          PUSHER_EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
-            "https://api.github.com/repos/${REPO}/commits/${COMMIT_SHA}" | jq -r '.commit.committer.email')
-          echo "PUSHER_EMAIL=${PUSHER_EMAIL}" >> $GITHUB_ENV
+  quality-gate-critical-permissions-check:
+    runs-on: ubuntu-latest
+    needs: quality-gate-code-check
+    if: ${{ needs.quality-gate-code-check.outputs.block-pr == 'false' }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-      - name: Upload CSV Report to Salesforce
-        run: |
-          if [ -s filtered-scanner-report.csv ]; then
-            contentDocumentResponse=$(curl -X POST https://your-salesforce-instance-url/services/data/v61.0/sobjects/ContentVersion/ \
-              -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}" \
-              -H "Content-Type: application/json" \
-              -d '{
-                "Title": "'"${{ env.FILE_TITLE }}"'",
-                "PathOnClient": "filtered-scanner-report.csv",
-                "VersionData": "'"$(cat filtered-scanner-report.csv)"'"
-              }')
-            echo "Response: $contentDocumentResponse"
-          else
-            echo "No scanner report generated, skipping upload."
-          fi
-        env:
-          SF_ACCESS_TOKEN: ${{ secrets.SF_ACCESS_TOKEN }}
-
-      - name: Send Email with actions-send-mail
-        uses: dawidd6/action-send-mail@v3
+      - name: Download Scanner Report
+        uses: actions/download-artifact@v3
         with:
-          server_address: "smtp.gmail.com"
-          server_port: "587"
-          username: ${{ secrets.GMAIL_EMAIL }}
-          password: ${{ secrets.GMAIL_APP_PASSWORD }}
-          from: ${{ secrets.GMAIL_EMAIL }}
-          subject: "SFDX Code Scan Delta Report"
-          body: "Please find the attached SFDX Code Scan Delta Report."
-          to: ${{ env.PUSHER_EMAIL }}, ${{ secrets.GMAIL_EMAIL }}
-          attachments: filtered-scanner-report.csv
+          name: SFDX_Code_Scan_Report
+
+      - name: Scan Profiles and Permission Sets for Critical Permissions
+        run: |
+          CRITICAL_PERMISSIONS=(
+              "AssignPermissionSets"
+              "AuthorApex"
+              "CustomizeApplication"
+              "FreezeUsers"
+              "ManageEncryptionKeys"
+              "ManageInternalUsers"
+              "ManagePasswordPolicies"
+              "ManageProfilesPermissionSets"
+              "ManageRoles"
+              "ManageSharing"
+              "ManageUsers"
+              "ModifyAllData"
+              "MonitorLoginHistory"
+              "MultiFactorAuthenticationRequired"
+              "PasswordNeverExpires"
+              "ResetPasswordsUnlockUsers"
+              "ViewAllData"
+          )
+
+          BLOCKED_FILES=()
+
+          for FILE in $(find force-app/main/default/profiles -name '*.profile-meta.xml'); do
+            for PERMISSION in "${CRITICAL_PERMISSIONS[@]}"; do
+              if grep -q "$PERMISSION" "$FILE" && ! grep -q "System Administrator" "$FILE"; then
+                BLOCKED_FILES+=("$FILE")
+              fi
+            done
+          done
+
+          for FILE in $(find force-app/main/default/permissionsets -name '*.permissionset-meta.xml'); do
+            for PERMISSION in "${CRITICAL_PERMISSIONS[@]}"; do
+              if grep -q "$PERMISSION" "$FILE"; then
+                BLOCKED_FILES+=("$FILE")
+              fi
+            done
+          done
+
+          if [ ${#BLOCKED_FILES[@]} -gt 0 ]; then
+            echo "Critical permissions found in the following files:"
+            for FILE in "${BLOCKED_FILES[@]}"; do
+              echo "$FILE"
+            done
+            exit 1
+          else
+            echo "No critical permissions assigned to non-System Administrator profiles or permission sets."
+          fi
