New Changes

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -1,5 +1,3 @@
-name: SFDX Code Scan Workflow
-
 on:
   push:
     branches:
@@ -9,8 +7,7 @@ jobs:
   installcli:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v3
         with:
           fetch-depth: 0
 
@@ -19,19 +16,19 @@ jobs:
         with:
           node-version: 20.x
 
-      - name: Install Salesforce CLI
+      - name: Install CLI
         run: npm install @salesforce/cli --global
 
-      - name: Install SFDX Scanner Plugin
+      - name: Install Scanner Plugin
         run: sf plugins install @salesforce/sfdx-scanner
 
-      - name: Verify Salesforce CLI Installation
+      - name: Verify SFDX CLI Installation
         run: sf --version
 
-      - name: Verify Scanner Plugin Installation
+      - name: Verify SFDX Scanner Plugin Installation
         run: sf plugins --core
 
-      - name: Get Changed Files
+      - name: Get changed files
         id: get-changes
         run: |
           git fetch --unshallow || true
@@ -54,8 +51,12 @@ jobs:
             echo "No relevant files changed."
             touch scanner-report.csv
           fi
+        env:
+          SF_LAZY_LOAD_MODULES: 'true'
+          SF_AUTOUPDATE_DISABLE: 'true'
+          SF_DISABLE_AUTOUPDATE: 'true'
 
-      - name: Encode CSV to Base64
+      - name: Encode CSV file to Base64
         if: success()
         id: encode_file
         run: |
@@ -66,14 +67,15 @@ jobs:
             exit 1
           fi
 
-      - name: Check Quality Gate
+      - name: Check Scanner Report Severity
         id: check_severity
         run: |
             if [ ! -f "scanner-report.csv" ]; then
               echo "Scanner report not found!"
               echo "QUALITY_GATE_STATUS=FAILED" >> $GITHUB_ENV
+              echo "::error file=scanner-report.csv::Scanner report not found!"
               exit 1
-            fi  # Closing the 'if' block
+            fi
         
             echo "Checking scanner report content:"
             cat scanner-report.csv  # Print CSV content to see what's inside
@@ -94,18 +96,25 @@ jobs:
               echo "::notice::Quality gate passed."
             fi
         
-
-      - name: Push Changes to Original Branch if Quality Gate Passed
-        if: success() && env.QUALITY_GATE_STATUS == 'PASSED'
+      - name: Revert changes if quality gate fails
+        if: failure()  # If the quality gate failed
         run: |
-          git config user.name "GitHub Actions"
-          git config user.email "actions@github.com"
-          git push origin HEAD  # Push the changes only if quality gate passed
+          git reset --hard HEAD~1  # Reset the branch to remove the failed commit
+          git push --force origin HEAD  # Force push to remove the commit from the branch
+
+      - name: Get Repository and Branch Info
+        id: get-info
+        run: |
+          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
+          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
+          COMMIT_LABEL=$(git log -1 --pretty=format:'%s')
+          FILE_TITLE="Code Scanner Delta Report_${REPO_NAME}_${BRANCH_NAME}_${COMMIT_LABEL}"
+          echo "FILE_TITLE=${FILE_TITLE}" >> $GITHUB_ENV
 
       - name: Upload Scanner Report as Artifact
         uses: actions/upload-artifact@v3
         with:
-          name: Scanner Report
+          name: ${{ env.FILE_TITLE }}
           path: scanner-report.csv
 
       - name: Get Pusher's Email
@@ -117,25 +126,54 @@ jobs:
             "https://api.github.com/repos/${REPO}/commits/${COMMIT_SHA}" | jq -r '.commit.committer.email')
           echo "PUSHER_EMAIL=${PUSHER_EMAIL}" >> $GITHUB_ENV
 
-      - name: Upload Report to Salesforce
-        if: success() && env.QUALITY_GATE_STATUS == 'PASSED'
+      - name: Upload CSV Report to Salesforce
+        if: success() && env.QUALITY_GATE_STATUS == 'PASSED'  # Only upload if quality gate passed
         run: |
-          contentDocumentResponse=$(curl -X POST https://instance.salesforce.com/services/data/v61.0/sobjects/ContentVersion/ \
+          if [ -s encoded_report.txt ]; then
+            contentDocumentResponse=$(curl -X POST https://individual-fc-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/ \
               -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}" \
               -H "Content-Type: application/json" \
-              -d '{"Title": "Scanner Report", "PathOnClient": "scanner-report.csv", "VersionData": "$(cat encoded_report.txt)"}')
-          echo "Salesforce upload complete."
+              -d '{
+                "Title": "'"${{ env.FILE_TITLE }}"'",
+                "PathOnClient": "scanner-report.csv",
+                "VersionData": "'"$(cat encoded_report.txt)"'"
+              }')
+            echo "Response: $contentDocumentResponse"
+            
+            contentVersionId=$(echo $contentDocumentResponse | jq -r '.id // empty')
+            if [ -z "$contentVersionId" ]; then
+              echo "Error: Failed to upload file. No ContentVersionId found."
+              exit 1
+            fi
+            echo "ContentVersionId: $contentVersionId"
+            
+            contentDocumentResponse=$(curl -X GET https://individual-fc-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/$contentVersionId \
+              -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}")
+            echo "ContentDocument Response: $contentDocumentResponse"
+            
+            contentDocumentId=$(echo $contentDocumentResponse | jq -r '.ContentDocumentId // empty')
+            if [ -z "$contentDocumentId" ]; then
+              echo "Error: Failed to retrieve ContentDocumentId. No ContentDocumentId found."
+              exit 1
+            fi
+            echo "ContentDocumentId: $contentDocumentId"
+          else
+            echo "No scanner report generated, skipping upload."
+          fi
+        env:
+          SF_ACCESS_TOKEN: ${{ secrets.SF_ACCESS_TOKEN }}
+        shell: bash
 
-      - name: Send Email Notification
+      - name: Send Email with actions-send-mail
         uses: dawidd6/action-send-mail@v3
-        if: env.QUALITY_GATE_STATUS == 'PASSED'
+        if: env.QUALITY_GATE_STATUS == 'PASSED'  # Only send email if quality gate passed
         with:
           server_address: 'smtp.gmail.com'
           server_port: '587'
           username: ${{ secrets.GMAIL_EMAIL }}
           password: ${{ secrets.GMAIL_APP_PASSWORD }}
           from: ${{ secrets.GMAIL_EMAIL }}
-          subject: 'SFDX Code Scan Report'
-          body: 'SFDX Code Scan Delta Report passed quality gate.'
-          to: ${{ env.PUSHER_EMAIL }}
+          subject: 'SFDX Code Scan Delta Report'
+          body: 'Please find the attached SFDX Code Scan Delta Report.'
+          to: ${{ env.PUSHER_EMAIL }}, ${{ secrets.GMAIL_EMAIL }}
           attachments: scanner-report.csv
