New Changes Pre-Commit

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -37,7 +37,7 @@ jobs:
           git fetch --unshallow || true
           if [ "$(git rev-list --count HEAD)" -gt "1" ]; then
             echo "Fetching changed files and lines between HEAD~1 and HEAD"
-            git diff --cached --unified=0 HEAD~1 HEAD > changes.diff || { echo "Failed to get git diff"; exit 1; }
+            git diff --unified=0 HEAD~1 HEAD > changes.diff || { echo "Failed to get git diff"; exit 1; }
           else
             echo "No previous commit to compare to." > changes.diff
           fi
@@ -52,8 +52,15 @@ jobs:
             BEGIN {valid_file=0} 
             /^diff --git/ {valid_file=0} 
             /\.cls$|\.lwc$/ {valid_file=1} 
-            /^@@/ && valid_file {split($0, arr, " "); gsub(",", "", arr[2]); start = substr(arr[2], 2); next}  
-            /^[+][^+]/ && valid_file {print "Line", start, ":", substr($0, 2)}  
+            /^@@/ && valid_file {
+              split($0, arr, " "); 
+              gsub(",", "", arr[2]);
+              old_start = substr(arr[2], 2); 
+              new_start = substr(arr[3], 2); 
+              next
+            }
+            /^[+][^+]/ && valid_file {print "Added Line", new_start++, ":", substr($0, 2)}
+            /^[^-+]/ && valid_file {print "Changed Line", old_start++, ":", $0}
           ' changes.diff | grep -v '^+++' > changed_cls_lwc_lines.txt
 
           if [ ! -s changed_cls_lwc_lines.txt ]; then
