New Changes Pre-Commit

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -1,72 +1,59 @@
-name: SFDX Code Scan Workflow
-
 on:
   pull_request:
     branches:
       - "**"
 
 jobs:
-  set-up-installation:
+  quality-gate-code-check:
     runs-on: ubuntu-latest
+    outputs:
+      scanner-report-path: ${{ steps.upload-report.outputs.artifact-path }}
+      block-pr: ${{ steps.block-check.outputs.block-status }}
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
+
       - name: Use Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 20.x
+
       - name: Install Salesforce CLI
         run: npm install @salesforce/cli --global
+
       - name: Install Scanner Plugin
         run: sf plugins install @salesforce/sfdx-scanner
+
       - name: Verify Salesforce CLI Installation
         run: sf --version
+
       - name: Verify Scanner Plugin Installation
         run: sf plugins --core
 
-  analyze-changed-files:
-    runs-on: ubuntu-latest
-    needs: set-up-installation
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Use Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: 20.x
-      - name: Install Salesforce CLI
-        run: npm install @salesforce/cli --global
-      - name: Install Scanner Plugin
-        run: sf plugins install @salesforce/sfdx-scanner
-
-      - name: Compare Previous Push and Current Commit
+      - name: Get changed files and lines (for .cls and .lwc files)
         id: get-changes
         run: |
-          # Fetch history for proper diff comparison
-          git fetch origin
-
-          # Compare the previous commit (HEAD~1) to the current HEAD of the branch
-          echo "Fetching changes between the previous pushed commit and the current commit on the branch"
-          git diff --unified=0 HEAD~1 HEAD > changes.diff || { echo "Failed to get git diff"; exit 1; }
+          git fetch --unshallow || true
+          if [ "$(git rev-list --count HEAD)" -gt "1" ]; then
+            echo "Fetching changed files and lines between HEAD~1 and HEAD"
+            git diff --unified=0 HEAD~1 HEAD > changes.diff || { echo "Failed to get git diff"; exit 1; }
+          else
+            echo "No previous commit to compare to." > changes.diff
+          fi
 
           if [ ! -s changes.diff ]; then
-            echo "No changes detected between the previous commit and the current commit."
+            echo "No changes detected between HEAD~1 and HEAD."
             exit 0
           fi
 
           echo "Processing changes for .cls and .lwc files only..."
           awk '
-            BEGIN {valid_file=0}
-            /^diff --git/ {valid_file=0}
-            /\.cls$|\.lwc$/ {valid_file=1}
-            /^@@/ && valid_file {
-              split($0, arr, " "); 
-              start = substr(arr[2], 2); 
-              next 
-            } 
-            /^[+][^+]/ && valid_file {print "Line", start++, ":", substr($0, 2)}
+            BEGIN {valid_file=0} 
+            /^diff --git/ {valid_file=0} 
+            /\.cls$|\.lwc$/ {valid_file=1} 
+            /^@@/ && valid_file {split($0, arr, " "); gsub(",", "", arr[2]); start = substr(arr[2], 2); line_offset=0; next}  
+            /^[+][^+]/ && valid_file {print "Line", start + line_offset++, ":", substr($0, 2)}  
           ' changes.diff | grep -v '^+++' > changed_cls_lwc_lines.txt
 
           if [ ! -s changed_cls_lwc_lines.txt ]; then
@@ -74,7 +61,6 @@ jobs:
             exit 0
           fi
 
-          echo "Printing current committed lines and line numbers:"
           cat changed_cls_lwc_lines.txt
 
       - name: Run SFDX Scanner on Changed Files and Lines
@@ -126,31 +112,6 @@ jobs:
           ' scanner-report.csv > filtered-scanner-report.csv
           cat filtered-scanner-report.csv
 
-      - name: Upload Filtered Scanner Report as Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: filtered-scanner-report
-          path: filtered-scanner-report.csv
-
-  block-pr-if-vulnerabilities-found:
-    runs-on: ubuntu-latest
-    needs: analyze-changed-files
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Use Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: 20.x
-      - name: Install Salesforce CLI
-        run: npm install @salesforce/cli --global
-      - name: Install Scanner Plugin
-        run: sf plugins install @salesforce/sfdx-scanner
-      - name: Download Filtered Scanner Report
-        uses: actions/download-artifact@v3
-        with:
-          name: filtered-scanner-report
       - name: Block PR merge if severity violations are found
         id: block-check
         run: |
@@ -159,71 +120,80 @@ jobs:
             echo "Severity 3 issues count: $severity_fail_count"
             if [ "$severity_fail_count" -gt 0 ]; then
               echo "Blocking your pull request due to severity 3 vulnerabilities found."
-              echo "block-status=true" >> $GITHUB_ENV
+              echo "::set-output name=block-status::true"
               exit 1
             else
               echo "No severity 3 vulnerabilities found. Proceeding with Approval."
-              echo "block-status=false" >> $GITHUB_ENV
+              echo "::set-output name=block-status::false"
             fi
           else
             echo "No filtered scanner report found."
             exit 1
           fi
 
-  uploading-the-artifact:
-    runs-on: ubuntu-latest
-    needs: [block-pr-if-vulnerabilities-found, analyze-changed-files] # This ensures it always runs after these jobs
-    if: always() # Ensures the job runs even if previous jobs fail
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Use Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: 20.x
-      - name: Install Salesforce CLI
-        run: npm install @salesforce/cli --global
-      - name: Install Scanner Plugin
-        run: sf plugins install @salesforce/sfdx-scanner
-      - name: Download Filtered Scanner Report
-        uses: actions/download-artifact@v3
-        with:
-          name: filtered-scanner-report
-
-      - name: Upload Filtered Scanner Report (Again)
+      - name: Upload Filtered Scanner Report
+        id: upload-report
+        if: always()
         uses: actions/upload-artifact@v3
         with:
           name: SFDX_Code_Scan_Report
           path: filtered-scanner-report.csv
 
+      - name: Install mailx
+        run: sudo apt-get install -y mailutils
+
+      - name: Get Repository and Branch Info
+        id: get-info
+        run: |
+          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
+          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
+          COMMIT_LABEL=$(git log -1 --pretty=format:'%s')
+          FILE_TITLE="Code Scanner Delta Report_${REPO_NAME}_${BRANCH_NAME}_${COMMIT_LABEL}"
+          echo "FILE_TITLE=${FILE_TITLE}" >> $GITHUB_ENV
+
+      - name: Upload Scanner Report as Artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ env.FILE_TITLE }}
+          path: filtered-scanner-report.csv
+
+      - name: Get Pusher's Email
+        id: get-pusher-email
+        run: |
+          COMMIT_SHA=${{ github.sha }}
+          REPO=${{ github.repository }}
+          PUSHER_EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
+            "https://api.github.com/repos/${REPO}/commits/${COMMIT_SHA}" | jq -r '.commit.committer.email')
+          echo "PUSHER_EMAIL=${PUSHER_EMAIL}" >> $GITHUB_ENV
+
+      - name: Send Email with actions-send-mail
+        if: always()
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: "smtp.gmail.com"
+          server_port: "587"
+          username: ${{ secrets.GMAIL_EMAIL }}
+          password: ${{ secrets.GMAIL_APP_PASSWORD }}
+          from: ${{ secrets.GMAIL_EMAIL }}
+          subject: "SFDX Code Scan Delta Report"
+          body: "Please find the attached SFDX Code Scan Delta Report."
+          to: ${{ env.PUSHER_EMAIL }}, ${{ secrets.GMAIL_EMAIL }}
+          attachments: filtered-scanner-report.csv
+
   quality-gate-critical-permissions-check:
     runs-on: ubuntu-latest
-    needs: block-pr-if-vulnerabilities-found
+    needs: quality-gate-code-check
     if: ${{ needs.quality-gate-code-check.outputs.block-pr == 'false' }}
     steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-
-      - name: Use Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: 20.x
-
-      - name: Install Salesforce CLI
-        run: npm install @salesforce/cli --global
-
-      - name: Install Scanner Plugin
-        run: sf plugins install @salesforce/sfdx-scanner
-
-      - name: Verify Salesforce CLI Installation
-        run: sf --version
-
-      - name: Verify Scanner Plugin Installation
-        run: sf plugins --core
+      - name: Checkout code
+        uses: actions/checkout@v3
 
       - name: Download Scanner Report
         uses: actions/download-artifact@v3
         with:
           name: SFDX_Code_Scan_Report
+
+      - name: Scan Profiles and Permission Sets for Critical Permissions
+        run: |
+          CRITICAL_PERMISSIONS=( "AssignPermissionSets" "AuthorApex" ... )
+          # Critical Permissions Check Logic
