Jira Story1

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -67,7 +67,8 @@ jobs:
           files=$(cat changed_files.txt | grep -E '\.cls$|\.lwc$' || true)
           echo "Files to scan: $files"
           if [ -n "$files" ]; then
-            sf scanner:run --target "$files" --format "csv" --outfile "scanner-report.csv" --ruleset "config/pmd/ruleset.xml" || { echo "Scanner run failed"; exit 1; }
+            # sf scanner:run --target "$files" --format "csv" --outfile "scanner-report.csv" --ruleset "config/pmd/ruleset.xml" || { echo "Scanner run failed"; exit 1; }
+            sf scanner:run --target "$files" --ruleset "config/pmd/ruleset.xml" --format "csv" --outfile "scanner-report.csv" --verbose || { echo "Scanner run failed"; exit 1; }
           else
             echo "No relevant files changed."
             touch scanner-report.csv
