Jira Story1

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -1,4 +1,4 @@
-name: SFDX Delta Report
+name: SFDX delta
 
 on:
   push:
@@ -49,14 +49,7 @@ jobs:
           files=$(cat changed_files.txt | grep -E '\.cls$|\.lwc$' || true)
           echo "Files to scan: $files"
           if [ -n "$files" ]; then
-            for file in $files; do
-              echo "Scanning file: $file"
-              # Run the scanner only on the lines that were changed
-              git diff HEAD~1 HEAD -- $file | sf scanner:run --target - --format "csv" --outfile "scanner-report-$file.csv" || { echo "Scanner run failed"; exit 1; }
-            done
-            # Combine all individual file reports into one
-            head -n 1 scanner-report-$(echo $files | awk '{print $1}').csv > scanner-report.csv
-            tail -n +2 -q scanner-report-*.csv >> scanner-report.csv
+            sf scanner:run --target "$files" --engine "pmd" --format "csv" --outfile "scanner-report.csv" || { echo "Scanner run failed"; exit 1; }
           else
             echo "No relevant files changed."
             touch scanner-report.csv
