Jira Story1

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -1,3 +1,5 @@
+name: SFDX Code Scan Delta
+
 on:
   push:
     branches:
@@ -56,25 +58,37 @@ jobs:
           SF_AUTOUPDATE_DISABLE: 'true'
           SF_DISABLE_AUTOUPDATE: 'true'
 
-      - name: Generate and Process Scanner Rule List
+      - name: Encode CSV file to Base64
         if: success()
+        id: encode_file
         run: |
-          # Run the command without --format
-          sf scanner:rule:list > scanner-rules.txt || { echo "Failed to generate rule list"; exit 1; }
+          if [ -f scanner-report.csv ]; then
+            base64 scanner-report.csv | tr -d '\n' > encoded_report.txt
+          else
+            echo "Scanner report CSV file not found."
+            exit 1
+          fi
 
-          # Process the output into CSV format
-          echo "name,languages,categories,rulesets [dep] engine,is dfa,is pilot" > scanner-rules.csv
-          tail -n +3 scanner-rules.txt | while IFS= read -r line; do
-            # Replace multiple spaces with commas
-            echo "$line" | sed -E 's/\s+/,/g' >> scanner-rules.csv
-          done
-        env:
-          SF_LAZY_LOAD_MODULES: 'true'
-          SF_AUTOUPDATE_DISABLE: 'true'
-          SF_DISABLE_AUTOUPDATE: 'true'
+      - name: Check Scanner Report Severity
+        id: check_severity
+        run: |
+          if [ ! -f "scanner-report.csv" ]; then
+            echo "Scanner report not found!"
+            echo "QUALITY_GATE_STATUS=FAILED" >> $GITHUB_ENV
+            echo "::error file=scanner-report.csv::Scanner report not found!"
+            exit 1
+          fi
 
-      - name: Install mailx
-        run: sudo apt-get install -y mailutils
+          SEVERITY_FAIL_COUNT=$(awk -F',' '$3 == "1" || $3 == "2" {count++} END {print count}' scanner-report.csv)
+          if [ "$SEVERITY_FAIL_COUNT" -gt 0 ]; then
+            echo "Quality gate failed due to high severity issues."
+            echo "QUALITY_GATE_STATUS=FAILED" >> $GITHUB_ENV
+            echo "::error::Quality gate failed due to high severity issues."
+          else
+            echo "Quality gate passed."
+            echo "QUALITY_GATE_STATUS=PASSED" >> $GITHUB_ENV
+            echo "::notice::Quality gate passed."
+          fi
 
       - name: Get Repository and Branch Info
         id: get-info
@@ -82,16 +96,14 @@ jobs:
           REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
           BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
           COMMIT_LABEL=$(git log -1 --pretty=format:'%s')
-          FILE_TITLE="SFDX_Code_Scan_Delta_${REPO_NAME}_${BRANCH_NAME}_${COMMIT_LABEL}.csv"
+          FILE_TITLE="Code Scanner Delta Report_${REPO_NAME}_${BRANCH_NAME}_${COMMIT_LABEL}"
           echo "FILE_TITLE=${FILE_TITLE}" >> $GITHUB_ENV
 
-      - name: Upload Scanner Report and Rules as Artifacts
+      - name: Upload Scanner Report as Artifact
         uses: actions/upload-artifact@v3
         with:
-          name: SFDX_Code_Scan_Delta
-          path: |
-            scanner-report.csv
-            scanner-rules.csv
+          name: ${{ env.FILE_TITLE }}
+          path: scanner-report.csv
 
       - name: Get Pusher's Email
         id: get-pusher-email
@@ -105,7 +117,7 @@ jobs:
       - name: Upload CSV Report to Salesforce
         if: success()
         run: |
-          if [ -s scanner-report.csv ]; then
+          if [ -s encoded_report.txt ]; then
             contentDocumentResponse=$(curl -X POST https://individual-fc-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/ \
               -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}" \
               -H "Content-Type: application/json" \
@@ -151,4 +163,4 @@ jobs:
           subject: 'SFDX Code Scan Delta Report'
           body: 'Please find the attached SFDX Code Scan Delta Report.'
           to: ${{ env.PUSHER_EMAIL }}, ${{ secrets.GMAIL_EMAIL }}
-          attachments: scanner-report.csv,scanner-rules.csv
+          attachments: scanner-report.csv
