Jira Story1

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -50,40 +50,38 @@ jobs:
       - name: Get Changed Files
         id: get-changes
         run: |
-          git fetch --unshallow || true
-          if [ "$(git rev-list --count HEAD)" -gt "1" ]; then
-            echo "Fetching changed files between HEAD~1 and HEAD"
-            git diff --name-only HEAD~1 HEAD > changed_files.txt
-          else
-            echo "No previous commit to compare to." > changed_files.txt
-          fi
-          cat changed_files.txt
-
-          - name: Run PMD Static Code Analysis
-          uses: pmd/pmd-github-action@v2
-          with:
-            rulesets: 'force-app/main/default/pmd/ruleset.xml' 
-            debug: true # Enable debug output
+            if [ "$(git rev-list --count HEAD)" -gt "1" ]; then
+              echo "Fetching changed files between HEAD~1 and HEAD"
+              git diff --name-only HEAD~1 HEAD > changed_files.txt
+            else
+              echo "No previous commit to compare to." > changed_files.txt
+            fi
+            cat changed_files.txt
   
-
+      - name: Run PMD Static Code Analysis
+        uses: pmd/pmd-github-action@v2
+        with:
+          rulesets: 'force-app/main/default/pmd/ruleset.xml' # Update the path to your custom ruleset
+  
       - name: Run SFDX Scanner on Changed Files
         if: success()
         run: |
-          files=$(cat changed_files.txt | grep -E '\.cls$|\.lwc$' || true)
-          echo "Files to scan: $files"
-          if [ -n "$files" ]; then
-            echo "Using custom ruleset: SFDX Code Scan Delta"
-            sf scanner:run --target "$files" --format "csv" --outfile "scanner-report.csv" --ruleset "force-app/main/default/pmd/ruleset.xml" || { echo "Scanner run failed"; exit 1; }
-            echo "Scanner report contents:"
-            cat scanner-report.csv
-          else
-            echo "No relevant files changed."
-            touch scanner-report.csv
-          fi
+            files=$(cat changed_files.txt | grep -E '\.cls$|\.lwc$' || true)
+            echo "Files to scan: $files"
+            if [ -n "$files" ]; then
+              echo "Using custom ruleset: SFDX Code Scan Delta"
+              sf scanner:run --target "$files" --format "csv" --outfile "scanner-report.csv" --ruleset "force-app/main/default/pmd/ruleset.xml" || { echo "Scanner run failed"; exit 1; }
+              echo "Scanner report contents:"
+              cat scanner-report.csv
+            else
+              echo "No relevant files changed."
+              touch scanner-report.csv
+            fi
         env:
           SF_LAZY_LOAD_MODULES: 'true'
           SF_AUTOUPDATE_DISABLE: 'true'
           SF_DISABLE_AUTOUPDATE: 'true'
+  
 
       - name: Encode CSV File to Base64
         if: success()
