Added Components Feature_1

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -1,10 +1,9 @@
-name: SFDX Code Scan
+name: SFDX Code Scan Delta
 
 on:
   push:
     branches:
-      - main
-      - '**'
+      - feature_1
 
 jobs:
   installcli:
@@ -34,11 +33,11 @@ jobs:
       - name: Get changed files
         id: get-changes
         run: |
-          # Fetch all commits to ensure we can reference HEAD~1
           git fetch --unshallow || true
           
           # Check if there is more than one commit
           if [ "$(git rev-list --count HEAD)" -gt "1" ]; then
+            echo "Fetching changed files between HEAD~1 and HEAD"
             git diff --name-only HEAD~1 HEAD > changed_files.txt
           else
             echo "No previous commit to compare to." > changed_files.txt
@@ -49,8 +48,9 @@ jobs:
         if: success()
         run: |
           files=$(cat changed_files.txt | grep -E '\.cls$|\.lwc$' || true)
+          echo "Files to scan: $files"
           if [ -n "$files" ]; then
-            sf scanner:run --target "$files" --format "csv" --outfile "scanner-report.csv"
+            sf scanner:run --target "$files" --format "csv" --outfile "scanner-report.csv" || { echo "Scanner run failed"; exit 1; }
           else
             echo "No relevant files changed."
             touch scanner-report.csv
@@ -64,7 +64,12 @@ jobs:
         if: success()
         id: encode_file
         run: |
-          base64 scanner-report.csv | tr -d '\n' > encoded_report.txt
+          if [ -f scanner-report.csv ]; then
+            base64 scanner-report.csv | tr -d '\n' > encoded_report.txt
+          else
+            echo "Scanner report CSV file not found."
+            exit 1
+          fi
 
       - name: Install jq
         if: success()
