New Changes

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -56,7 +56,7 @@ jobs:
  
       # Step 8: Create a temporary workspace directory
       - name: Create Temporary Workspace
-        run: mkdir temp_workspace
+        run: mkdir -p temp_workspace
  
       # Step 9: Get list of changed files
       - name: Get Changed Files
@@ -71,15 +71,10 @@ jobs:
           fi
           cat temp_workspace/changed_files.txt
 
-      # Step 9: Get list of changed files and stash the changes
-      - name: Stash Changes
-        run: |
-          git stash --include-untracked
-          git stash list
-        
       # Step 10: Run SFDX Scanner only on relevant changed files (.cls and .lwc files)
       - name: Run SFDX Scanner on Changed Files
         run: |
+          mkdir -p temp_workspace
           files=$(cat temp_workspace/changed_files.txt | grep -E '\.cls$|\.lwc$' || true)
           echo "Files to scan: $files"
           if [ -n "$files" ]; then
@@ -96,32 +91,27 @@ jobs:
      # Step 11: Parse the JSON report and check if there are violations
       - name: Check for Violations
         run: |
-          if jq -e '.[] | select(.'"severity":\s*3')' temp_workspace/scanner-report.json > /dev/null; then
-            echo "Severity 3 code violations found, blocking the commit."
-            exit 1  # This will halt the workflow and prevent the commit
+          if [ -f temp_workspace/scanner-report.json ]; then
+            if jq -e '.[] | select(.'"severity":\s*3')' temp_workspace/scanner-report.json > /dev/null; then
+              echo "Severity 3 code violations found, blocking the commit."
+              exit 1
+            else
+              echo "No severity 3 code violations found."
+            fi
           else
-            echo "No severity 3 code violations found."
+            echo "Scanner report not found. Skipping."
           fi
 
-      # Step 13: If no violations, apply stashed changes and commit
-      - name: Apply Stashed Changes and Commit
-        if: success()
-        run: |
-          git stash pop
-          git add .
-          git commit -m "Code changes after successful scan"
-          git push
- 
       # Step 12: Encode CSV report to Base64
       - name: Encode CSV File to Base64
         run: |
           if [ -f temp_workspace/scanner-report.json ]; then
             base64 temp_workspace/scanner-report.json | tr -d '\n' > temp_workspace/encoded_report.txt
           else
-            echo "Scanner report CSV file not found."
+            echo "Scanner report JSON file not found."
             exit 1
           fi
- 
+
       # Step 13: Install mailx for email notifications
       - name: Install mailx
         run: sudo apt-get install -y mailutils
